### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by extsoft** [qaivanpleten/repspark_ios_tests#1]
Items like 
- `.idea`
- `.DS_Store`
- `geckodriver.log`

have not to be a part of the code base. Please remove them, create `.gitignore` file and add these patterns to the file.

**Comment by qaivanpleten** [comment]
It seems like I got this issue during adding .idea folder to gitignore 
https://github.com/hsz/idea-gitignore/issues/340

**Comment by qaivanpleten** [comment]
Done
