### ISSUE TITLE
Organize some structure of the code

### ISSUE THREAD

**Issue by extsoft** [qaivanpleten/repspark_ios_tests#3]
Please organize project structure based on this guide: https://github.com/tatools/demo-python.
There is one example how it is implemented: https://github.com/tatools/demo-python.

**Comment by qaivanpleten** [comment]
Correct me if I'm wrong. In my vision there should be 3 folders: 
1. commons:
/actions/
/elements/
/mobile_functions
                
2. tests: 
/test_cases

3. test_reports

Other files will be in root folder

**Comment by extsoft** [comment]
@qaivanpleten, I propose the following structure:
```
├── repspark_at # main package for python's code, including tests
│   ├── actions
│   ├── elements
│   ├── .....
│   └── ios_tests # package for iOS tests (may be there will be other types)
├── reports # folder for the tests reports (has to be removed from git in future)
├── ....
```
```
