### ISSUE TITLE
Make path to repspark.app relative

### ISSUE THREAD

**Issue by extsoft** [qaivanpleten/repspark_ios_tests#4]
`app` capability has hardcoded absolute path: `"/Users/user/Desktop/RepSpark-App/ios/build/Build/Products/Debug-iphonesimulator/repspark.app"`. It's a bad thing as it will work only on one PC. 
Suggested solution: 
1. Add `repspark.app` to the git 
2. Configure relative path instead of absolute in the tests.

**Comment by qaivanpleten** [comment]
Напишу українською, бо тут багато тексту.
Я не впевнений що це можливо, бо це Іос аплікуха. Наприклад, я не можу просто передати цей файл на девайс і встановити аплікуху чи запустити її, я можу тільки зробити білд безпосередньо на телефон, або зробити білд і викласти його а апп-стор.
На скільки я розумію тут та сама фігня. Викласти в гіт можу але воно не буде працювати. 
В тесті в мене прописаний повний шлях до файлу в папці проекту. проект у мене встановлений локально. 
Якби у нас був якийсь дженкінс чи докер, на якому лежав би проект, то я міг би використати твій підхід.

Що думаєш?

**Comment by extsoft** [comment]
Anyway, I can't run tests now on my local because the path is hardcoded. That's why let's try to hardcode at least relative path. 
Project structure:
```
$ ls -l .../projects
repspark_ios_tests     # the root directory for the tests
RepSpark-ios-app      # the root directory for the app
```

And then we can access the app from tests root like `../RepSpark-ios-app/....` - this path will be the same for custom laptops.

@qaivanpleten what do you think?

**Comment by extsoft** [comment]
Not relevant.
